[profile.debug]
incremental = true # Incremental builds

[profile.release]
incremental = true # Incremental builds, even for release
strip = true       # Automatically strip symbols from the binary.
opt-level = "z"    # Optimize for size.
lto = true         # Link-time optimiation

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
ar = "arm-linux-gnueabihf-ar"
