[build]
target-dir = "build" # path of where to place all generated artifacts

[profile.debug]
incremental = true # Incremental builds

[profile.release]
incremental = true # Incremental builds, even for release
strip = true       # Automatically strip symbols from the binary.
opt-level = "z"    # Optimize for size.
lto = true         # Link-time optimiation
