name: Publish Docker Images

on:
  release:
    types: [published]
  push:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ijmclinden/rocket-notify
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{major}},value=${{ env.TAG }},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
