name: Rust Build, Test, & Release

on:
  pull_request:
  push:
    branches: ["main"]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

jobs:
  style:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - name: cargo clippy
        run: cargo clippy --all -- -D warnings -W clippy::pedantic

  test:
    name: Test
    needs: [style]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: cargo build
        run: cargo build --verbose
      - name: cargo test
        run: cargo test --verbose --all-features

  build_linux:
    name: Build Linux
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: linux-amd64
            target: x86_64-unknown-linux-gnu
            packages: g++-x86-64-linux-gnu
          - name: linux-aarch64
            target: aarch64-unknown-linux-gnu
            packages: g++-aarch64-linux-gnu
          - name: linux-armhf
            target: arm-unknown-linux-gnueabihf
            packages: g++-arm-linux-gnueabihf
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: install ${{ matrix.packages }}
        if: matrix.packages != ''
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ${{ matrix.packages }}
      - name: cargo build ${{ matrix.target }}
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
      - name: package
        if: ${{ github.event_name == 'release' }}
        shell: bash
        run: |
          tar -czvf rocket-notify-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release/ rocket-notify
      - uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: "rocket-notify*"

  build_macos:
    name: Build macOS
    needs: [test]
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: cargo build ${{ matrix.target }}
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
      - name: package
        if: ${{ github.event_name == 'release' }}
        shell: bash
        run: |
          tar -czvf rocket-notify-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release/ rocket-notify
      - uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: "rocket-notify*"

  build_windows:
    name: Build Windows
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: windows-amd64
            target: x86_64-pc-windows-gnu
            packages: g++-mingw-w64-x86-64
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: install ${{ matrix.packages }}
        if: matrix.packages != ''
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ${{ matrix.packages }}
      - name: cargo build ${{ matrix.target }}
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
      - name: package
        if: ${{ github.event_name == 'release' }}
        shell: bash
        run: |
          tar -czvf rocket-notify-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release/ rocket-notify.exe
      - uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: "rocket-notify*"
