name: Rust Build, Test, & Release

on:
  pull_request:
  push:
    branches: ["main"]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

jobs:
  style:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - name: Clippy
        run: cargo clippy --all -- -D warnings -W clippy::pedantic

  test:
    name: Test
    needs: [style]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose --all-features

  deploy_linux:
    name: Deploy Linux
    needs: [test]
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            aarch64-unknown-linux-gnu,
            arm-unknown-linux-gnueabihf,
          ]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          tar -czvf rocket-notify-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release/ rocket-notify
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "rocket-notify*"

  deploy_macos:
    name: Deploy macOS
    needs: [test]
    if: ${{ github.event_name == 'release' }}
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          tar -czvf rocket-notify-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release/ rocket-notify
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "rocket-notify*"

  deploy_windows:
    name: Deploy Windows
    needs: [test]
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          tar -czvf rocket-notify-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release/ rocket-notify.exe
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "rocket-notify*"
